config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  get 'events/ryder_cup', to: 'events#ryder_cup'
  get 'events/knockout', to: 'events#knockout'
  resources :events, only: [:index, :show]
  resources :reports, only: [:index, :show]
  resources :honours, only: [:index]
  get 'honours/roll_of_honour', to: 'honours#roll_of_honour'
  get 'honours/eclectic', to: 'honours#eclectic'
  get 'honours/putting', to: 'honours#putting'
  get 'honours/knockout', to: 'honours#knockout'
  get 'honours/ryder_cup', to: 'honours#ryder_cup'
  resources :scores, only: [:index]
  get 'scores/eclectic', to: 'scores#eclectic'
  get 'scores/putting', to: 'scores#putting'
  get 'scores/handicaps', to: 'scores#handicaps'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :reports

  scope :regular, -> { where('regular_event = ?', true) }

end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :event

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.where('event_date >= ?', Date.today).order('event_date ASC')
  end

  def show
    @event = Event.find(params[:id])
  end

  def ryder_cup
    @event = Event.where(event_type: 'ryder_cup')
  end

  def knockout
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end

end

app/controllers/honours_controller.rb
class HonoursController < ApplicationController

  def index
  end

  def roll_of_honour
  end

  def eclectic
  end

  def putting
  end

  def knockout
  end

  def ryder_cup
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
  end

  def show
    @report = Report.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
  end

  def eclectic
  end

  def putting
  end

  def handicaps
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<section class="main">

  <p style="padding:0px; margin:0px">Click on the event to load up more information including maps:<br><br></p>
  <article class="quarterly">
    <% @events.regular.each do |event| %>
      <h4><%= link_to("#{l event.event_date} - #{event.location} - #{number_to_currency(event.cost)}", event_path(event)) %></h4>
      <%# if event.reports.any? %>
        <%# event.reports.each do |report| %>
          <%# link_to("#{report.sub_title}", report_path(report)) %>
        <%# end %>
      <%# end %>
    <% end %>
  </article>
  <article class="specialist">
    <h4><%= link_to('Knockout Competition 2016', events_knockout_path) %></a><br>
    <br>
    <%= link_to('Ryder Cup 2018', events_ryder_cup_path) %><br></h4>
  </article>
</section>

app/views/events/knockout.html.erb
<section class="main">
  <h4>Last 32</h4>
  <p>Lord Les (32) vs Sam D (12)</p>
  <p>Phil P (19) vs Rhys D (7)</p>
  <p>Adrian G (19) vs Stephen G (32)</p>
  <p>Nigel G (26) vs Biffa M (8)</p>
  <p>Graham H (17) vs Miles J (8)</p>
  <p>Judge (26) vs Paul B (19)</p>
  <p>DOB (17) vs Ben G (20)</p>
  <p>Graham K (13) vs Jimmy R (21)</p>
  <p><strong>Phil D (12)</strong> vs David C (9)</p>
  <p><strong>Kevin S (22)</strong> vs Bye</p>
  <p>Andy G (15) vs James F (26)</p>
  <p>Trevor D (18) vs David G (32)</p>
  <p>Simon T (12) vs Mark K (4)</p>
  <p><strong>Colin D (24)</strong> vs Fayed Al Salem (14)</p>
  <p>Lee D (0) vs Taylor H (32)</p>
  <p>Dan R (17) vs Mark H (18)</p>
</section>

app/views/events/ryder_cup.html.erb
<section class="main">
  <!-- <h3><%# l @event.event_date %> - <%# @event.location %> - <%# number_to_currency(@event.cost) %></h3> -->
  <h3>Details to follow...</h3>
  <article class="info">
    <h4>Holders: Youngs (Lee D)</h4>
    <!-- <p style="padding:5px; margin:5px"><%# @event.description %> Deposit <%# number_to_currency(@event.deposit) %></p> -->
    <!-- <h4><%# link_to("Click here for Course Website", @event.website, target: "_blank") %></h4> -->
  </article>
  <article class="map">
    <!-- <iframe src="<%# @event.map %>" width="400" height="300" frameborder="0" style="border:0"></iframe> -->
  </article>
</section>

app/views/events/show.html.erb
<section class="main">
  <h3><%= l @event.event_date %> - <%= @event.location %> - <%= number_to_currency(@event.cost) %></h3>
  <article class="info">
    <h4>Holder: <%= @event.holder %></h4>
    <p style="padding:5px; margin:5px"><%= @event.description %> Deposit <%= number_to_currency(@event.deposit) %></p>
    <h4><%= link_to("Click here for Course Website", @event.website, target: "_blank") %></h4>
  </article>
  <article class="map">
    <iframe src="<%= @event.map %>" width="400" height="300" frameborder="0" style="border:0"></iframe>
  </article>
</section>

app/views/home/show.html.erb
  <section class="main">
    <div class="budget">
      <em>Stan's Balance:<br>
      &pound;<%= ENV['BALANCE']%></em>
    </div>
    <%= t('home.main_text').html_safe %>
  </section>

app/views/honours/eclectic.html.erb
<section class="main">
  <p class="introline">The Peter Thake Trophy (Eclectic)</p>
  <table>
    <th class="eclectic">Year</th>
    <th class="nametwo">Stan</th>
    <th class="eclectic">Points</th>
    <tr>
      <td class="eclectic">2015</td>
      <td class="nametwo">Lee D</td>
      <td class="eclectic">47</td>
    </tr>
    <tr>
      <td class="eclectic">2014</td>
      <td class="nametwo">Simon T</td>
      <td class="eclectic">47</td>
    </tr>
    <tr>
      <td class="eclectic">2013</td>
      <td class="nametwo">Joseph F</td>
      <td class="eclectic">54</td>
    </tr>
    <tr>
      <td class="eclectic">2012</td>
      <td class="nametwo">Byron M &amp; Dan R</td>
      <td class="eclectic">49</td>
    </tr>
    <tr>
      <td class="eclectic">2011</td>
      <td class="nametwo">Kevin S</td>
      <td class="eclectic">52</td>
    </tr>
    <tr>
      <td class="eclectic">2010</td>
      <td class="nametwo">Phil D</td>
      <td class="eclectic">48</td>
    </tr>
    <tr>
      <td class="eclectic">2009</td>
      <td class="nametwo">Ben G</td>
      <td class="eclectic">48</td>
    </tr>
    <tr>
      <td class="eclectic">2008</td>
      <td class="nametwo">Neill T</td>
      <td class="eclectic">47</td>
    </tr>
    <tr>
      <td class="eclectic">2007</td>
      <td class="nametwo">Phil P</td>
      <td class="eclectic">51</td>
    </tr>
    <tr>
      <td class="eclectic">2006</td>
      <td class="nametwo">Neill T</td>
      <td class="eclectic">50</td>
    </tr>
    <tr>
      <td class="eclectic">2005</td>
      <td class="nametwo">Joseph F</td>
      <td class="eclectic">51</td>
    </tr>
    <tr>
      <td class="eclectic">2004</td>
      <td class="nametwo">Stephen G</td>
      <td class="eclectic">54</td>
    </tr>
    <tr>
      <td class="eclectic">2003</td>
      <td class="nametwo">Stephen G</td>
      <td class="eclectic">51</td>
    </tr>
    <tr>
      <td class="eclectic">2002</td>
      <td class="nametwo">Adrian G &amp; Andy G</td>
      <td class="eclectic">47</td>
    </tr>
    <tr>
      <td class="eclectic">2001</td>
      <td class="nametwo">Joseph F &amp; Phil P</td>
      <td class="eclectic">46</td>
    </tr>
    <tr>
      <td class="eclectic">2000</td>
      <td class="nametwo">Neill T</td>
      <td class="eclectic">51</td>
    </tr>
    <tr>
      <td class="eclectic">1997</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">50</td>
    </tr>
  </table>
</section>

app/views/honours/index.html.erb
<section class="main">
  <h4><%= link_to('Stans Golf Roll Of Honour', honours_roll_of_honour_path) %></h4>
  <h4><%= link_to('The Peter Thake Trophy (Eclectic)', honours_eclectic_path) %></h4>
  <h4><%= link_to('The Blair Dunlop Trophy (Putting)', honours_putting_path) %></h4>
  <h4><%= link_to('The Knockout Trophy', honours_knockout_path) %></h4>
  <h4><%= link_to('Ryder Cups', honours_ryder_cup_path) %></h4>
</section>

app/views/honours/knockout.html.erb
<section class="main">
  <p class="introline">Knockout Winners and Losing Finalists</p>
  <table>
    <th class="eclectic">Year</th>
    <th class="nametwo">Winner</th>
    <th class="nametwo">Runner-Up</th>
    <tr>
      <td class="eclectic">2015</td>
      <td class="nametwo shade">Lee D</td>
      <td class="nametwo">Trevor D</td>
    </tr>
    <tr>
      <td class="eclectic">2014</td>
      <td class="nametwo shade">David C</td>
      <td class="nametwo">Kevin S</td>
    </tr>
    <tr>
      <td class="eclectic">2013</td>
      <td class="nametwo shade">Graham K</td>
      <td class="nametwo">Dan R</td>
    </tr>
    <tr>
      <td class="eclectic">2012</td>
      <td class="nametwo shade">Byron M</td>
      <td class="nametwo">Neill T</td>
    </tr>
    <tr>
      <td class="eclectic">2011</td>
      <td class="nametwo shade">Colin D</td>
      <td class="nametwo">David Cr</td>
    </tr>
  </table>
</section>

app/views/honours/putting.html.erb
<section class="main">
  <p class="introline">The Blair Dunlop Trophy (Putting)</p>
  <table>
    <th class="eclectic">Year</th>
    <th class="nametwo">Stan</th>
    <th class="eclectic">Putts</th>
    <tr>
      <td class="eclectic">2015</td>
      <td class="nametwo">Graham K &amp; Nigel G</td>
      <td class="eclectic">125</td>
    </tr>
    <tr>
      <td class="eclectic">2014</td>
      <td class="nametwo">Adrian G &amp; Andy G</td>
      <td class="eclectic">127</td>
    </tr>
    <tr>
      <td class="eclectic">2013</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">120</td>
    </tr>
    <tr>
      <td class="eclectic">2012</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">121</td>
    </tr>
    <tr>
      <td class="eclectic">2011</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">129</td>
    </tr>
    <tr>
      <td class="eclectic">2010</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">125</td>
    </tr>
    <tr>
      <td class="eclectic">2009</td>
      <td class="nametwo">Byron M</td>
      <td class="eclectic">125</td>
    </tr>
    <tr>
      <td class="eclectic">2008</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">128</td>
    </tr>
    <tr>
      <td class="eclectic">2007</td>
      <td class="nametwo">Blair D &amp; Andy G</td>
      <td class="eclectic">120</td>
    </tr>
    <tr>
      <td class="eclectic">2006</td>
      <td class="nametwo">Andy G</td>
      <td class="eclectic">125</td>
    </tr>
    <tr>
      <td class="eclectic">2005</td>
      <td class="nametwo">Kevin S</td>
      <td class="eclectic">127</td>
    </tr>
    <tr>
      <td class="eclectic">2003</td>
      <td class="nametwo">Blair D</td>
      <td class="eclectic">132</td>
    </tr>
    <tr>
      <td class="eclectic">2004</td>
      <td class="nametwo">Blair D</td>
      <td class="eclectic">105</td>
    </tr>
  </table>
</section>

app/views/honours/roll_of_honour.html.erb
<section class="main">
  <p class="introline">Events won since May 1993. Hover over the numbers to list details.</p>
  <table>
    <th class="name">Stan</th>
    <th class="number">Spring</th>
    <th class="number">Summer</th>
    <th class="number">Autumn</th>
    <th class="number">Winter</th>
    <th class="number">Total</th>
    <tr>
      <td>Andy G</td>
      <td class="number" title="Ufford Park 97, The Hertfordshire 07">2</td>
      <td class="number" title="The Warren 93, Ufford Park 95">2</td>
      <td class="number" title="The Warren 94, The Warren 97, Forest of Arden 98, Ufford Park 09, Channels 00, Benton Hall 02, Ufford Park 09">6</td>
      <td class="number" title="Bushey Hall 07">1</td>
      <td class="total">11</td>
    </tr>
    <tr class="shade">
      <td>Adrian G</td>
      <td class="number" title="Barnham Broom 96, Rio Formosa 02, Benton Hall 04">3</td>
      <td class="number" title="Ufford Park 97, Benton Hall 00">2</td>
      <td class="number" title="Toot Hill 12">1</td>
      <td class="number" title="Forest of Arden 98, Bushey Hall 06">2</td>
      <td class="total">8</td>
    </tr>
    <tr>
      <td>Kevin S</td>
      <td class="number" title="Upminster 95">1</td>
      <td class="number" title="Sandy Lodge 99">1</td>
      <td class="number" title="Toot Hill 14">1</td>
      <td class="number" title="The Warren 93, The Hertfordshire 97, Nazeing 00, Mentmore 02">4</td>
      <td class="total">7</td>
    </tr>
    <tr class="shade">
      <td>Phil P</td>
      <td class="number" title="The Warren 94, The Warren 99, The Hertfordshire 09">3</td>
      <td class="number" title="The Warren 94, Benton Hall 03">2</td>
      <td class="number" title="The Warren 05, Colchester 15">2</td>
      <td class="number">0</td>
      <td class="total">7</td>
    </tr>
    <tr >
      <td>Neill T</td>
      <td class="number">0</td>
      <td class="number" title="Barnham Broom 96, Forest of Arden 98, The Warren 06,">3</td>
      <td class="number" title="West Essex 96">1</td>
      <td class="number" title="The Warren 94, Channels 95">2</td>
      <td class="total">6</td>
    </tr>
    <tr class="shade">
      <td>Byron M</td>
      <td class="number" title="Bushey Hall 05">1</td>
      <td class="number" title="The Warren 09">1</td>
      <td class="number" title="Bushey Hall 03, Benton Hall 13">2</td>
      <td class="number" title="Ufford Park 01">1</td>
      <td class="total">5</td>
    </tr>
    <tr>
      <td>Blair D</td>
      <td class="number" title="The Warren 03">1</td>
      <td class="number">0</td>
      <td class="number" title="Forest of Arden 99, Ufford Park 06">2</td>
      <td class="number" title="Forest of Arden 99">1</td>
      <td class="total">4</td>
    </tr>
    <tr class="shade">
      <td>Nigel W</td>
      <td class="number" title="Bearsted Park 98, The Hertfordshire 00">2</td>
      <td class="number" title="Villa Sol 01">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">3</td>
    </tr>
    <tr>
      <td>Joseph F</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="Bushey Hall 01">1</td>
      <td class="number" title="Benton Hall 09, Toot Hill 13">2</td>
      <td class="total">3</td>
    </tr>
    <tr class="shade">
      <td>Mark H</td>
      <td class="number" title="The Hertfordshire 08">1</td>
      <td class="number" title="Millennium 02">1</td>
      <td class="number" title="The Warren 08">1</td>
      <td class="number">0</td>
      <td class="total">3</td>
    </tr>
    <tr>
      <td>Miles J</td>
      <td class="number">0</td>
      <td class="number" title="Victoria 10">1</td>
      <td class="number" title="Crondon Park 04">1</td>
      <td class="number" title="The Hertfordshire 05">1</td>
      <td class="total">3</td>
    </tr>
    <tr class="shade">
      <td>Trevor D</td>
      <td class="number">0</td>
      <td class="number" title="The Warren 07, Colchester 14">2</td>
      <td class="number">0</td>
      <td class="number" title="Ufford Park 08">1</td>
      <td class="total">3</td>
    </tr>
    <tr>
      <td>Jimmy R</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="The Warren 95">1</td>
      <td class="number" title="The Hertfordshire 96">1</td>
      <td class="total">2</td>
    </tr>
    <tr class="shade">
      <td>David Ch</td>
      <td class="number" title="Quinta Do Lago 01">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="Channels 03">1</td>
      <td class="total">2</td>
    </tr>
    <tr>
      <td>Glen S</td>
      <td class="number">0</td>
      <td class="number" title="Ufford Park 04">1</td>
      <td class="number" title="Ufford Park 07">1</td>
      <td class="number">0</td>
      <td class="total">2</td>
    </tr>
    <tr class="shade">
      <td>Nigel G</td>
      <td class="number">0</td>
      <td class="number" title="Stockbrook Manor 05, Toot Hill 11">2</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">2</td>
    </tr>
    <tr>
      <td>Phil D</td>
      <td class="number" title="The Hertfordshire 06">1</td>
      <td class="number" title="The Hertfordshire 13">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">2</td>
    </tr>
    <tr class="shade">
      <td>Danny R</td>
      <td class="number" title="The Warren 11">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="The Warren 12">1</td>
      <td class="total">2</td>
    </tr>
    <tr>
      <td>David Cr</td>
      <td class="number">0</td>
      <td class="number" title="Stockbrook Manor 08">1</td>
      <td class="number">0</td>
      <td class="number" title="Nazeing 14">1</td>
      <td class="total">2</td>
    </tr>
    <tr class="shade">
      <td>Colin D</td>
      <td class="number" title="Bentley GC 15">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="Colchester 11">1</td>
      <td class="total">2</td>
    </tr>
    <tr>
      <td>Graham K</td>
      <td class="number" title="The Warren 13">1</td>
      <td class="number" title="The Warren 15">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">2</td>
    </tr>
    <tr class="shade">
      <td>Lee D</td>
      <td class="number" title="The Hertfordshire 12">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="The Hertfordshire 15">1</td>
      <td class="total">2</td>
    </tr>
    <tr>
      <td>Stephen G</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="Channels 04">1</td>
      <td class="total">1</td>
    </tr>
    <tr class="shade">
      <td>Rhys D</td>
      <td class="number" title="Laguna 10">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">1</td>
    </tr>
    <tr>
      <td>Dave S</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="Colchester 10">1</td>
      <td class="number">0</td>
      <td class="total">1</td>
    </tr>
    <tr class="shade">
      <td>Ben G</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="The Hertfordshire 10">1</td>
      <td class="total">1</td>
    </tr>
    <tr>
      <td>Sam D</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number" title="The Hertfordshire 11">1</td>
      <td class="number">0</td>
      <td class="total">1</td>
    </tr>
    <tr class="shade">
      <td>Simon T</td>
      <td class="number">0</td>
      <td class="number" title="Colchester 12">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">1</td>
    </tr>
    <tr>
      <td>Graham H</td>
      <td class="number" title="The Hertfordshire 14">1</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="number">0</td>
      <td class="total">1</td>
    </tr>
  </table>
</section>

app/views/honours/ryder_cup.html.erb
<section class="main">
  <p class="introline">Ryder Cup Winners.</p>
  <table>
    <th class="eclectic">Year</th>
    <th class="nametwo">Winner</th>
    <th class="nametwo">Captain</th>
     <tr>
      <td class="eclectic">2015</td>
      <td class="nametwo">Youngs</td>
      <td class="nametwo">Lee D</td>
    </tr>
    <tr>
      <td class="eclectic">2013</td>
      <td class="nametwo">Youngs</td>
      <td class="nametwo">Colin D</td>
    </tr>
    <tr>
      <td class="eclectic">2011</td>
      <td class="nametwo">Youngs</td>
      <td class="nametwo">James F</td>
    </tr>
    <tr>
      <td class="eclectic">2009</td>
      <td class="nametwo">Youngs</td>
      <td class="nametwo">Sam D</td>
    </tr>
    <tr>
      <td class="eclectic">2007</td>
      <td class="nametwo">Olds</td>
      <td class="nametwo">Miles J</td>
    </tr>
    <tr>
      <td class="eclectic">2005</td>
      <td class="nametwo">Olds</td>
      <td class="nametwo">Phil P</td>
    </tr>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stans Golf Society - Driving And Slicing Since May 1993</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51507465-1', 'stansgolf.co.uk');
  ga('send', 'pageview');

</script>
</head>
<body>
  <div class="wrapper">
    <header>
      <h1>Stans</h1>
      <h2>Participants of Planet Golf</h2>
    </header>
    <nav>
      <ul>
        <li><%= link_to('Home', root_path) %></li>
        <li><%= link_to('Events', events_path) %></li>
        <li><%= link_to('Scores & Caps', scores_path) %></li>
        <li><%= link_to('Honours', honours_path) %></li>
        <li><%= link_to('Reports', reports_path) %></li>
      </ul>
    </nav>
    <%= yield %>
    <footer>
      <p style="padding:0px; margin:0px" id="dateLastMod">stansgolf.co.uk is produced and maintained by Athlone Developments. <!-- <a href="http://www.athlonedevelopments.co.uk">Click here to return to athlonedevelopments.co.uk.</a> --> <br>Last Updated: <%= ENV['LAST_UPDATED']%>
      </p>
    </footer>
  </div>
</body>
</html>

app/views/reports/index.html.erb
<section class="main">
  <p style="padding:0px; margin:0px">
    Enjoy previous reports by clicking on the links below:
  </p>
  <% Report.all.order('created_at DESC').each do |report| %>
    <h4><%= link_to("#{report.main_title}", report_path(report)) %></h4>
  <% end %>
</section>

app/views/reports/show.html.erb
<section class="main">
  <h3><%= @report.main_title %> - <%= @report.sub_title %></h3>
  <%= @report.body.html_safe %>
</section>

app/views/scores/index.html.erb
<section class="main">
  <h4><%= link_to('Eclectic Scores 2016', scores_eclectic_path) %></h4>
  <h4><%= link_to('Putting Scores 2016', scores_putting_path) %></h4>
  <h4><%= link_to('Handicaps 2016', scores_handicaps_path) %></h4>
</section>